### ISSUE TITLE
Regression in 1.6 using enum values(dynamic and static)

### ISSUE THREAD

**Issue by BlueHotDog** [absinthe-graphql/absinthe#1040]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```
* Absinthe version (mix deps | grep absinthe):
```
* absinthe 1.6.1 (Hex package) (mix)
  locked at 1.6.1 (absinthe) f0105f1d
* absinthe_plug 1.5.4 (Hex package) (mix)
  locked at 1.5.4 (absinthe_plug) 80360cd8
```
* Client Framework and version (Relay, Apollo, etc):
Not relevant
### Expected behavior

```
enum(:xxx, values: [:red, :green, :blue, :alpha])
object :zzz do
    field(:yyy, :xxx)
end
```
to work.

### Actual behavior
Since elixir produce terrible error messages with protocol implementation, i changed Absinthe.Schema.sdl.ex:70 to:
      {:ok, Absinthe.Schema.Notation.SDL.Render.inspect(blueprint, %{pretty: true})}

And it produces this nice error:
```
** (ArgumentError) you attempted to apply :module on [:red, :green, :blue, :alpha]. If you are using apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
    :erlang.apply([:red, :green, :blue, :alpha], :module, [])
    (absinthe 1.6.1) lib/absinthe/schema/notation/sdl_render.ex:384: anonymous fn/1 in Absinthe.Schema.Notation.SDL.Render.render_list/3
    (elixir 1.11.3) lib/enum.ex:3479: Enum.reject_list/2
    (absinthe 1.6.1) lib/absinthe/schema/notation/sdl_render.ex:384: Absinthe.Schema.Notation.SDL.Render.render_list/3
    (absinthe 1.6.1) lib/absinthe/schema/notation/sdl_render.ex:195: Absinthe.Schema.Notation.SDL.Render.render/2
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (absinthe 1.6.1) lib/absinthe/schema/notation/sdl_render.ex:63: Absinthe.Schema.Notation.SDL.Render.render/2
    (absinthe 1.6.1) lib/absinthe/schema/notation/sdl_render.ex:11: Absinthe.Schema.Notation.SDL.Render.inspect/2
    (absinthe 1.6.1) lib/mix/tasks/absinthe.schema.sdl.ex:70: Mix.Tasks.Absinthe.Schema.Sdl.generate_schema/1
    (absinthe 1.6.1) lib/mix/tasks/absinthe.schema.sdl.ex:52: Mix.Tasks.Absinthe.Schema.Sdl.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
```

**Comment by binaryseed** [comment]
Thanks, fix here: https://github.com/absinthe-graphql/absinthe/pull/1041

**Comment by BlueHotDog** [comment]
Thanks! waiting for the new version.
