### ISSUE TITLE
Union with type list_of(:type) not working

### ISSUE THREAD

**Issue by Awlexus** [absinthe-graphql/absinthe#1047]
If submitting a bug, please provide the following:

### Environment

* Elixir version:
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]
Elixir 1.11.3 (compiled with Erlang/OTP 21)
* Absinthe version:
  * absinthe 1.6.3 (Hex package) (mix)
  * absinthe_plug 1.5.5 (Hex package) (mix)

### Expected behavior
I tried to make a union type like the following, but it resulted in a compilation error
```elixir
union :my_union do
  types [:boolean, list_of(:id)]
end
```

### Actual behavior
The following error was thrown. I tried to check if lists are supported for union types, but didn't find anything specific regarding this scenario. To me, it seems Absinthe would support this, if the `list_of` macro would have been expanded correctly.  
```elixir
== Compilation error in file lib/my_app/graphql/schema.ex ==
** (FunctionClauseError) no function clause matching in Absinthe.Blueprint.TypeReference.unwrap/1

    The following arguments were given to Absinthe.Blueprint.TypeReference.unwrap/1:

        # 1
        {:list_of, [line: 22], [:id]}

    Attempted function clauses (showing 4 out of 4):

        def unwrap(%Absinthe.Blueprint.TypeReference.Name{} = value)
        def unwrap(%Absinthe.Blueprint.TypeReference.Identifier{} = value)
        def unwrap(value) when is_atom(value)
        def unwrap(%struct{of_type: inner}) when struct === Absinthe.Blueprint.TypeReference.List or struct === Absinthe.Blueprint.TypeReference.NonNull

    (absinthe 1.6.3) lib/absinthe/blueprint/type_reference.ex:18: Absinthe.Blueprint.TypeReference.unwrap/1
    (absinthe 1.6.3) lib/absinthe/phase/schema/validation/type_references_exist.ex:93: Absinthe.Phase.Schema.Validation.TypeReferencesExist.unwrap/1
    (absinthe 1.6.3) lib/absinthe/phase/schema/validation/type_references_exist.ex:75: Absinthe.Phase.Schema.Validation.TypeReferencesExist.check_or_error/3
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.6.3) lib/absinthe/phase/schema/validation/type_references_exist.ex:20: Absinthe.Phase.Schema.Validation.TypeReferencesExist.validate_schema/1
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
```

**Comment by benwilson512** [comment]
Hi @Awlexus the error could definitely be better. However, the GraphQL spec only allows unions between objects.

https://spec.graphql.org/draft/#sec-Unions

> GraphQL Unions represent an object that could be one of a list of GraphQL Object types

I'll open a separate issue addressing the error message.
