### ISSUE TITLE
Cannot generate SDL for :persistent_term schema

### ISSUE THREAD

**Issue by dolfinus** [absinthe-graphql/absinthe#1054]
### Environment

* Elixir version (elixir -v): 1.11.3
* Absinthe version (mix deps | grep absinthe): 1.6.3
* Client Framework and version (Relay, Apollo, etc): -

### Expected behavior

If I try to execute `absinthe.schema.sdl` or `absinthe.schema.json`, I expect to see a file output:
```bash
absinthe.schema.sdl --schema ArkenstonWeb.Schema graphql/schema.graphql
# graphql/schema.graphql is created and filled up with schema SDL

absinthe.schema.json --schema ArkenstonWeb.Schema --pretty graphql/schema.json
# graphql/schema.json is created and filled up with schema JSON
```

### Actual behavior

It is broken when I use a `:persistent_term` schema:
https://github.com/dolfinus/arkenston-backend/runs/2160087638
```
* creating graphql
* creating graphql/schema.graphql
** (ArgumentError) argument error
    :persistent_term.get({Absinthe.Schema.PersistentTerm, ArkenstonWeb.Schema})
    (absinthe 1.6.3) lib/absinthe/schema/persistent_term.ex:91: Absinthe.Schema.PersistentTerm.get/1
    (absinthe 1.6.3) lib/absinthe/schema/persistent_term.ex:51: Absinthe.Schema.PersistentTerm.__absinthe_type__/2
    (absinthe 1.6.3) lib/absinthe/phase/schema.ex:107: Absinthe.Phase.Schema.set_schema_node/4
    (absinthe 1.6.3) lib/absinthe/phase/schema.ex:71: anonymous fn/4 in Absinthe.Phase.Schema.set_children/3
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.6.3) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

### Relevant Schema/Middleware Code
https://github.com/dolfinus/arkenston-backend/blob/68b588fa0b56aaed256d4836a136e4cff1b6f25f/lib/arkenston_web/schema.ex#L1-L5
```elixir
defmodule ArkenstonWeb.Schema do
  use Absinthe.Schema

  @schema_provider Absinthe.Schema.PersistentTerm
...
end
```

According to documentation https://hexdocs.pm/absinthe/Absinthe.Schema.PersistentTerm.html I've added this line to my supervisor tree:
https://github.com/dolfinus/arkenston-backend/blob/68b588fa0b56aaed256d4836a136e4cff1b6f25f/lib/arkenston/application.ex#L19
```
{Absinthe.Schema, MyAppWeb.Schema}
```

It works absolutely fine in staging or tests because Application is being started here.
But schema export command does not start it, and IMHO is should not do that because it may require to start too many things, like a database.

**Comment by binaryseed** [comment]
Right, the task doesn't start the app. I believe we can just start `Absinthe.Schema` with the schema module directly, all it does is populate the `persistent_term`

**Comment by benwilson512** [comment]
@binaryseed shouldn't the `on_load` thing we did populate it without starting the genserver?

**Comment by dolfinus** [comment]
@benwilson512 Do you mean this @on_load which was removed in October 2020?
https://github.com/absinthe-graphql/absinthe/pull/985/files#diff-bb15e00e34ca6f23ba5da5239df0922d2ac098d091839bb5b8cf66cd95ab8285L113

**Comment by binaryseed** [comment]
Yes there were some odd issues with that technique. I'd love to find one that didn't require users to put `Absinthe.Schema` in the supervision tree, though it's not the biggest deal

**Comment by benwilson512** [comment]
Ah I forgot it was removed.

**Comment by dolfinus** [comment]
Actually, I don't see any issues with `@on_load` usage for starting the scheme module. What do you think about returning it back?

**Comment by benwilson512** [comment]
@dolfinus I believe we ran into edge cases where it did not work. @binaryseed do you remember the details there?

**Comment by binaryseed** [comment]
The note I left when I reverted was this: https://github.com/absinthe-graphql/absinthe/pull/985#issuecomment-719877948

I intend to try again though, it would be nice

**Comment by jordi-chacon** [comment]
Encountering exact same error when running `absinthe.schema.json` Mix task. This is preventing us is from using `persistent_term`. Curious if there are any workarounds or any plans to fix this issue in the next version of Absinthe?

**Comment by dolfinus** [comment]
It looks like #1159 fixed this issue

**Comment by connorjacobsen** [comment]
Interestingly, I still run into this error on `1.7.0` when running `mix absinthe.schema.json --schema MySchema`, but running `mix absinthe.schema.sdl --schema MySchema` works fine. I get the same error as the original comment.

**Comment by kdawgwilk** [comment]
@connorjacobsen I think 1.7.0 is older than the fix that was merged and has not been released in a new version yet

**Comment by connorjacobsen** [comment]
@kdawgwilk That would make sense! Thank you.

**Comment by dolfinus** [comment]
How about releasing 1.7.0? Latest release was a year ago

**Comment by connorjacobsen** [comment]
1.7.0 was released in January.

You can point your mix.exs file to a commit in a pinch.

**Comment by dolfinus** [comment]
![Screenshot_20221021-005233_GitHub.png](https://user-images.githubusercontent.com/4661021/197066086-cc7cd488-d45e-488c-87b1-ffa9e8dfe0fa.png)
I see, it look like something went wrong with Github Releases, there are no 1.6.8 and 1.7.0 releases.

Nevertheless, that's quite a lot of time since the latest release

**Comment by connorjacobsen** [comment]
Yes the issue must be on the GitHub side of things since 1.7.0 is released on [hex.pm](https://hex.pm/packages/absinthe). But yeah, that was in January.

**Comment by kdawgwilk** [comment]
I think there is a tag for 1.7.0 but not a release in GitHub

**Comment by benwilson512** [comment]
The canonical release list is hex, not github.
