### ISSUE TITLE
Absinthe doesn't conform to GraphQL spec for validating schemas with interfaces that implement other interfaces

### ISSUE THREAD

**Issue by stellanor** [absinthe-graphql/absinthe#1080]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Absinthe version (mix deps | grep absinthe): absinthe 1.6.4
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

When defining a schema with a higher-order interface, for example, interface `Mammal` implements interface `Animal`, and object type `Dog` implements `Mammal` (and therefore `Dog` transitively implements `Animal`)...

I expect compilation of object types in that schema to enforce the [interface transitivity requirement of the GraphQL spec](https://github.com/graphql/graphql-spec/blob/main/spec/Section%203%20--%20Type%20System.md#interfaces):

> Transitively implemented interfaces (interfaces implemented by the interface that is being implemented) must also be defined on an implementing type or interface. For example, Image cannot implement Resource without also implementing Node

### Actual behavior

However, when defining an absinthe schema such as this `Dog`/`Mammal`/`Animal` example, if I only explicitly implement `Mammal` on `Dog`, I do not get a compilation error about the missing `Animal` interface declaration, and instead, I get runtime errors when resolving queries that spread on the various types. Here is an example.

My test schema:

```
defmodule AbsintheTestSchema do
  use Absinthe.Schema

  interface :animal do
    field :name, :string
    field :leg_count, :integer
    resolve_type fn
      %{breed: _}, _ -> :dog
      _, _ -> nil
    end
  end

  interface :mammal do
    interface :animal
    field :name, :string
    field :leg_count, :integer
    field :has_fur, :boolean

    resolve_type fn
      %{breed: _}, _ -> :dog
      _, _ -> nil
    end
  end

  object :dog do
    interface :mammal
    field :breed, :string
    field :name, :string
    field :leg_count, :integer
    field :has_fur, :boolean
  end

  query do
    field :my_animal, :animal do
      resolve fn _, _ ->
         {:ok, %{name: "Ponyo", leg_count: 4, has_fur: true, breed: "pitbull" }}
      end
    end
  end
end
```

Then I hop into iex with this test project, and define this query string:

```
{
  myAnimal {
    name
    ... on Mammal {
      hasFur
    }
    ... on Dog {
      breed
    }
  }
}
```

Passing that query string into `Absinthe.run(AbsintheTestSchema)` gives me these resolution errors:

```
{:ok,
 %{
   errors: [
     %{
       locations: [%{column: 5, line: 4}],
       message: "Fragment spread has no type overlap with parent.\nParent possible types: [\"Mammal\"]\nSpread possible types: [\"Dog\"]\n"
     },
     %{
       locations: [%{column: 5, line: 7}],
       message: "Fragment spread has no type overlap with parent.\nParent possible types: [\"Mammal\"]\nSpread possible types: [\"Dog\"]\n"
     }
   ]
 }}
```

If I change the definition of `:dog` to explicitly implement both interfaces (`interfaces [:mammal, :animal]`), then recompile and run the same query, it works as expected, and gives me this result:

```
{:ok,
 %{
   data: %{
     "myAnimal" => %{"breed" => "pitbull", "hasFur" => true, "name" => "Ponyo"}
   }
 }}
```

In contrast, I tested this with graphql-js (given that it is a reference implementation of the GraphQL spec), and a similar schema does not pass the validation--it gives me this error, which I expect absinthe to give also:

```
{
  errors: [
    GraphQLError [Object]: Type Dog must implement Animal because it is implemented by Mammal.
        at SchemaValidationContext.reportError (/Users/epoley/node_modules/graphql/type/validate.js:86:19)
        at validateTypeImplementsAncestors (/Users/epoley/node_modules/graphql/type/validate.js:379:15)
        at validateInterfaces (/Users/epoley/node_modules/graphql/type/validate.js:293:5)
        at validateTypes (/Users/epoley/node_modules/graphql/type/validate.js:209:7)
        at validateSchema (/Users/epoley/node_modules/graphql/type/validate.js:52:3)
        at graphqlImpl (/Users/epoley/node_modules/graphql/graphql.js:79:62)
        at /Users/epoley/node_modules/graphql/graphql.js:28:59
        at new Promise (<anonymous>)
        at graphql (/Users/epoley/node_modules/graphql/graphql.js:26:10)
        at Object.<anonymous> (/Users/epoley/code/test_graphql_js/test.js:42:1) {
      locations: [Array]
    }
  ]
}
```

This was a surprise to me when I used higher-order interfaces in GraphQL for the first time in absinthe. My assumption (coming from other languages with higher-order protocols and interfaces) was that I'd only need to explicitly implement `Mammal` on `Dog`, which was how I wrote the erroneous code. It's fine that GraphQL specifies that transitivity must be explicitly defined on the object type, but it's confusing that Absinthe doesn't enforce this when validating a schema.

### Relevant Schema/Middleware Code

(provided above)

**Comment by tlvenn** [comment]
Hi  @maartenvanvliet  I believe you did the initial work to implement this feature, is there any chance you could have a look at this bug ? Thanks in advance !

**Comment by binaryseed** [comment]
@stellanor Could you look at the PR that was merged & validate that it resolves the issue?

**Comment by stellanor** [comment]
I verified using latest master today (1ad9f67d27f229bdd207626dfb47d8bebf3b6250) that this is fixed and that the schema fails to compile, as expected. I tested this both with my mammal/animal sample schema, as well as the real-world production schema where I discovered this originally. 

Sorry for the delay in the validation, and thanks all for the fix!
