### ISSUE TITLE
Interface implementing other interfaces does not seem to work with is_type_of

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#1123]
### Environment

* Elixir version (elixir -v): 1.12.3 with OTP 24
* Absinthe version (mix deps | grep absinthe): 1.6.6

### Expected behavior

I have an existing schema where I am trying to introduce interfaces implementing other interfaces.
I don't use / define `resolve_type` in my interfaces, instead I implement `is_type_of` in all the objects that implement interfaces.

I would expect that existing queries would still work.

### Actual behavior

Existing queries over objects that now uses interfaces that implements other interfaces are crashing:

```
(KeyError) key :is_type_of not found in: %Absinthe.Type.Interface{__private__.....
       (absinthe 1.6.6) lib/absinthe/type.ex:44: Absinthe.Type.function/2
       (absinthe 1.6.6) lib/absinthe/type/interface.ex:106: anonymous fn/2 in Absinthe.Type.Interface.resolve_type/4
       (elixir 1.12.3) lib/enum.ex:3862: Enum.find_list/3
       (absinthe 1.6.6) lib/absinthe/type/interface.ex:105: Absinthe.Type.Interface.resolve_type/4
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:125: Absinthe.Phase.Document.Execution.Resolution.resolve_fields/4
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:280: Absinthe.Phase.Document.Execution.Resolution.build_result/3
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:280: Absinthe.Phase.Document.Execution.Resolution.build_result/3
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
       (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
       (absinthe 1.6.6) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
       (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
       (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
       (phoenix 1.6.0) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
       (phoenix 1.6.0) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
```

![image](https://user-images.githubusercontent.com/3340262/143280616-ec0d9463-d69b-42f7-9a34-54880d8bfd93.png)

I suspect that `implementors` in line 89 actually contains interfaces as well as objects implementing the given interface instead of the just having concrete objects which leads to the above error.

@maartenvanvliet what do you think ?

**Comment by tlvenn** [comment]
I have submitted a simple PR to filter the list to only include objects and now all is working fine.

**Comment by tlvenn** [comment]
I just realized that the issue has been reported already and there is even a PR...
Duplicate of https://github.com/absinthe-graphql/absinthe/issues/1077
