### ISSUE TITLE
"understanding subscriptions" documentation needs to be updated

### ISSUE THREAD

**Issue by Qqwy** [absinthe-graphql/absinthe#1190]
The ['Understanding Subscriptions'](https://hexdocs.pm/absinthe/subscriptions.html) page in the documentation explains how to start using subscriptions.

However, a couple of parts seem out of date:
- The default PubSub settings in the config seem to use a different syntax than the current one.
- The page lists changes to make for phoenix 1.5 and 1.4 and in places 1.3. Not all of the steps that are accurate for 1.5 seem to translate to 1.6 however. The part about adding your socket only shows changes for v1.3/v1.4 and v1.2 and before.
- The page guides you to include `absinthe_phoenix ~> 1.5`. However, the current version is 2.0.2.

**Comment by Qqwy** [comment]
After trying to follow the instructions best as possible, I get the following compile-time error. I think it might be related, but maybe it is not.

```elixir
== Compilation error in file lib/heartbeat_web/schema.ex ==
** (KeyError) key :type_definitions not found in: %Absinthe.Blueprint.Schema.ObjectTypeDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 45}, module: HeartbeatWeb.Schema}, description: nil, directives: [], errors: [], fields: [%Absinthe.Blueprint.Schema.FieldDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 55}, module: HeartbeatWeb.Schema}, arguments: [%Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 56}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :id, module: HeartbeatWeb.Schema, name: "id", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :id}}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 57}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :url, module: HeartbeatWeb.Schema, name: "url", placement: :argument_definition, source_location: nil, type: :string}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 58}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :interval_msec, module: HeartbeatWeb.Schema, name: "interval_msec", placement: :argument_definition, source_location: nil, type: :integer}], complexity: nil, config: nil, default_value: nil, deprecation: nil, description: "Update a Monitored URL configuration", directives: [], errors: [], flags: %{}, function_ref: {:mutation, :monitored_url_update}, identifier: :monitored_url_update, middleware: [{:{}, [], [{Absinthe.Resolution, :call}, {:&, [line: 60], [{:/, [line: 60], [{{:., [line: 60], [{:__aliases__, [counter: {HeartbeatWeb.Schema, 63}, line: 60], [:HeartbeatWeb, :Resolvers, :Content]}, :update_monitored_url]}, [no_parens: true, line: 60], []}, 3]}]}]}], module: HeartbeatWeb.Schema, name: "monitored_url_update", source_location: nil, triggers: {:%{}, [], []}, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :monitored_url}}, %Absinthe.Blueprint.Schema.FieldDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 47}, module: HeartbeatWeb.Schema}, arguments: [%Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 48}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :url, module: HeartbeatWeb.Schema, name: "url", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :string}}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 49}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :interval_msec, module: HeartbeatWeb.Schema, name: "interval_msec", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :integer}}], complexity: nil, config: nil, default_value: nil, deprecation: nil, description: "Create a Monitored URL configuration", directives: [], errors: [], flags: %{}, function_ref: {:mutation, :monitored_url_create}, identifier: :monitored_url_create, middleware: [{:{}, [], [{Absinthe.Resolution, :call}, {:&, [line: 51], [{:/, [line: 51], [{{:., [line: 51], [{:__aliases__, [counter: {HeartbeatWeb.Schema, 63}, line: 51], [:HeartbeatWeb, :Resolvers, :Content]}, :create_monitored_url]}, [no_parens: true, line: 51], []}, 3]}]}]}], module: HeartbeatWeb.Schema, name: "monitored_url_create", source_location: nil, triggers: {:%{}, [], []}, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :monitored_url}}], flags: %{}, identifier: :mutation, imports: [], interface_blueprints: [], interfaces: [], is_type_of: nil, module: HeartbeatWeb.Schema, name: "RootMutationType", source_location: nil}
    :erlang.map_get(:type_definitions, %Absinthe.Blueprint.Schema.ObjectTypeDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 45}, module: HeartbeatWeb.Schema}, description: nil, directives: [], errors: [], fields: [%Absinthe.Blueprint.Schema.FieldDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 55}, module: HeartbeatWeb.Schema}, arguments: [%Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 56}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :id, module: HeartbeatWeb.Schema, name: "id", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :id}}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 57}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :url, module: HeartbeatWeb.Schema, name: "url", placement: :argument_definition, source_location: nil, type: :string}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 58}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :interval_msec, module: HeartbeatWeb.Schema, name: "interval_msec", placement: :argument_definition, source_location: nil, type: :integer}], complexity: nil, config: nil, default_value: nil, deprecation: nil, description: "Update a Monitored URL configuration", directives: [], errors: [], flags: %{}, function_ref: {:mutation, :monitored_url_update}, identifier: :monitored_url_update, middleware: [{:{}, [], [{Absinthe.Resolution, :call}, {:&, [line: 60], [{:/, [line: 60], [{{:., [line: 60], [{:__aliases__, [counter: {HeartbeatWeb.Schema, 63}, line: 60], [:HeartbeatWeb, :Resolvers, :Content]}, :update_monitored_url]}, [no_parens: true, line: 60], []}, 3]}]}]}], module: HeartbeatWeb.Schema, name: "monitored_url_update", source_location: nil, triggers: {:%{}, [], []}, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :monitored_url}}, %Absinthe.Blueprint.Schema.FieldDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 47}, module: HeartbeatWeb.Schema}, arguments: [%Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 48}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :url, module: HeartbeatWeb.Schema, name: "url", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :string}}, %Absinthe.Blueprint.Schema.InputValueDefinition{__private__: [], __reference__: %{location: %{file: "/run/media/qqwy/Serendipity/Programming/Vanpelt/heartbeat/lib/heartbeat_web/schema.ex", line: 49}, module: HeartbeatWeb.Schema}, default_value: nil, default_value_blueprint: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, identifier: :interval_msec, module: HeartbeatWeb.Schema, name: "interval_msec", placement: :argument_definition, source_location: nil, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :integer}}], complexity: nil, config: nil, default_value: nil, deprecation: nil, description: "Create a Monitored URL configuration", directives: [], errors: [], flags: %{}, function_ref: {:mutation, :monitored_url_create}, identifier: :monitored_url_create, middleware: [{:{}, [], [{Absinthe.Resolution, :call}, {:&, [line: 51], [{:/, [line: 51], [{{:., [line: 51], [{:__aliases__, [counter: {HeartbeatWeb.Schema, 63}, line: 51], [:HeartbeatWeb, :Resolvers, :Content]}, :create_monitored_url]}, [no_parens: true, line: 51], []}, 3]}]}]}], module: HeartbeatWeb.Schema, name: "monitored_url_create", source_location: nil, triggers: {:%{}, [], []}, type: %Absinthe.Blueprint.TypeReference.NonNull{errors: [], of_type: :monitored_url}}], flags: %{}, identifier: :mutation, imports: [], interface_blueprints: [], interfaces: [], is_type_of: nil, module: HeartbeatWeb.Schema, name: "RootMutationType", source_location: nil})
    (elixir 1.13.1) lib/map.ex:275: Map.update!/3
    (absinthe 1.7.0) lib/absinthe/blueprint/schema.ex:193: Absinthe.Blueprint.Schema.build_types/3
    (absinthe 1.7.0) expanding macro: Absinthe.Schema.Notation.__before_compile__/1
    lib/heartbeat_web/schema.ex:1: HeartbeatWeb.Schema (module)

```

### Version information:
- absinthe v1.7.0
- absinthe_plug v1.5.8
- absinthe_phoenix v2.0.2
- phoenix v1.6.11
- phoenix_pubsub v2.1.1
- Elixir v1.13.1
- Erlang/OTP v25

**Comment by maartenvanvliet** [comment]
> *EDIT*: This was caused by something else, namely that I added a subscription inside a mutation :sweat_smile: .
> 

Do you have an example of this? I think we can show a more meaningful error.
