### ISSUE TITLE
Deprecated calling of function (without parenthesis) not supported in elixir 1.17 and OTP 27

### ISSUE THREAD

**Issue by tairosonloa** [absinthe-graphql/absinthe#1332]
We are using absinthe as dep, but it uses deprecated code and it prevents us to upgrade our service to elixir 1.17 and OTP 27.

I'll work on a PR to fix this right away :)

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 25)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.6.8 (Hex package) (mix)
  locked at 1.6.8 (absinthe) 188045f0
* absinthe_plug 1.5.8 (Hex package) (mix)
  locked at 1.5.8 (absinthe_plug) bbb04176
```

* Client Framework and version (Relay, Apollo, etc):

_Does not apply_

### Expected behavior

The lib won't have deprecated code, so it will be able to compile the project when using the `--warnings-as-errors` flag to compile.

### Actual behavior

The code won't compile due to deprecated code:

```
Compiling 153 files (.ex)
warning: using map.field notation (without parentheses) to invoke function Absinthe.Blueprint.Schema.ObjectTypeDefinition.functions() is deprecated, you must add parentheses instead: remote.function()
  (absinthe 1.6.6) lib/absinthe/blueprint/schema.ex:62: Absinthe.Blueprint.Schema.functions/1
  (absinthe 1.6.6) lib/absinthe/schema/notation.ex:1842: Absinthe.Schema.Notation.functions_for_type/2
  (absinthe 1.6.6) lib/absinthe/schema/notation.ex:1828: Absinthe.Schema.Notation.lift_functions/3
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
  (elixir 1.17.2) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
  (elixir 1.17.2) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
  (absinthe 1.6.6) lib/absinthe/schema/notation.ex:1781: Absinthe.Schema.Notation."MACRO-__before_compile__"/2
  (elixir 1.17.2) src/elixir_dispatch.erl:261: :elixir_dispatch.expand_macro_fun/7
  (elixir 1.17.2) src/elixir_dispatch.erl:156: :elixir_dispatch.dispatch_require/7
  (elixir 1.17.2) src/elixir_module.erl:460: :elixir_module.expand_callback/6
  (stdlib 6.0.1) lists.erl:2146: :lists.foldl/3
  (elixir 1.17.2) src/elixir_module.erl:430: :elixir_module.eval_form/7
  (elixir 1.17.2) src/elixir_module.erl:129: :elixir_module.compile/7
  (elixir 1.17.2) src/elixir_compiler.erl:38: :elixir_compiler.maybe_fast_compile/2
  (elixir 1.17.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.17.2) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.17.2) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8

warning: using map.field notation (without parentheses) to invoke function WololoWeb.Schema.__absinthe_pipeline_modifiers__() is deprecated, you must add parentheses instead: remote.function()
  (absinthe 1.6.6) lib/absinthe/schema.ex:340: Absinthe.Schema.apply_modifiers/2
  (absinthe 1.6.6) lib/absinthe/schema.ex:357: Absinthe.Schema.__after_compile__/2
  (elixir 1.17.2) src/elixir_module.erl:461: anonymous fn/6 in :elixir_module.expand_callback/6
  (elixir 1.17.2) src/elixir_module.erl:460: :elixir_module.expand_callback/6
  (stdlib 6.0.1) lists.erl:2146: :lists.foldl/3
  (elixir 1.17.2) src/elixir_module.erl:198: :elixir_module.compile/7
  (elixir 1.17.2) src/elixir_compiler.erl:38: :elixir_compiler.maybe_fast_compile/2
  (elixir 1.17.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.17.2) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.17.2) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8

warning: using map.field notation (without parentheses) to invoke function WololoWeb.Schema.__absinthe_blueprint__() is deprecated, you must add parentheses instead: remote.function()
  (absinthe 1.6.6) lib/absinthe/schema.ex:359: Absinthe.Schema.__after_compile__/2
  (elixir 1.17.2) src/elixir_module.erl:461: anonymous fn/6 in :elixir_module.expand_callback/6
  (elixir 1.17.2) src/elixir_module.erl:460: :elixir_module.expand_callback/6
  (stdlib 6.0.1) lists.erl:2146: :lists.foldl/3
  (elixir 1.17.2) src/elixir_module.erl:198: :elixir_module.compile/7
  (elixir 1.17.2) src/elixir_compiler.erl:38: :elixir_compiler.maybe_fast_compile/2
  (elixir 1.17.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.17.2) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.17.2) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8

warning: using map.field notation (without parentheses) to invoke function Absinthe.Type.BuiltIns.Scalars.__absinthe_blueprint__() is deprecated, you must add parentheses instead: remote.function()
  (absinthe 1.6.6) lib/absinthe/phase/schema/type_imports.ex:38: Absinthe.Phase.Schema.TypeImports.do_imports/3
  (absinthe 1.6.6) lib/absinthe/phase/schema/type_imports.ex:21: Absinthe.Phase.Schema.TypeImports.handle_imports/1
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
  (elixir 1.17.2) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
  (elixir 1.17.2) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
  (absinthe 1.6.6) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
  (absinthe 1.6.6) lib/absinthe/phase/schema/type_imports.ex:10: Absinthe.Phase.Schema.TypeImports.run/2
  (absinthe 1.6.6) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
  (absinthe 1.6.6) lib/absinthe/schema.ex:360: Absinthe.Schema.__after_compile__/2
  (elixir 1.17.2) src/elixir_module.erl:461: anonymous fn/6 in :elixir_module.expand_callback/6
  (elixir 1.17.2) src/elixir_module.erl:460: :elixir_module.expand_callback/6
  (stdlib 6.0.1) lists.erl:2146: :lists.foldl/3
  (elixir 1.17.2) src/elixir_module.erl:198: :elixir_module.compile/7
  (elixir 1.17.2) src/elixir_compiler.erl:38: :elixir_compiler.maybe_fast_compile/2
  (elixir 1.17.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.17.2) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.17.2) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8

Compilation failed due to warnings while using the --warnings-as-errors option
```

### Relevant Schema/Middleware Code

_Does not apply_

**Comment by benwilson512** [comment]
Hi, the latest version of Absinthe is `1.7.8` and this version has the necessary changes already.
