### ISSUE TITLE
v1.2: Can't find type `__type` for GraphiQL

### ISSUE THREAD

**Issue by sjchmiela** [absinthe-graphql/absinthe#173]
This happened when I opened GraphiQL in v1.2
```
[error] #PID<0.479.0> running Sheetly.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Absinthe.Phase.Document.Execution.Resolution.find_target_type/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:247: Absinthe.Phase.Document.Execution.Resolution.find_target_type(%Absinthe.Type.List{of_type: :__type}, Sheetly.Schema)
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:240: Absinthe.Phase.Document.Execution.Resolution.field_applies?/4
        (elixir) lib/enum.ex:787: anonymous fn/3 in Enum.filter/2
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:787: Enum.filter/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:64: Absinthe.Phase.Document.Execution.Resolution.resolve_fields/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:163: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:232: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:187: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:74: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:163: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:74: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:41: Absinthe.Phase.Document.Execution.Resolution.resolve_operation/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:28: Absinthe.Phase.Document.Execution.Resolution.run/2
        (absinthe) lib/absinthe/pipeline.ex:190: Absinthe.Pipeline.run_phase/3
        lib/absinthe/plug.ex:87: Absinthe.Plug.execute/2
        lib/absinthe/plug.ex:54: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:154: Phoenix.Router.Route.forward/4
        (sheetly) lib/phoenix/router.ex:261: Sheetly.Router.dispatch/2
        (sheetly) web/router.ex:1: Sheetly.Router.do_call/2
```

**Comment by benwilson512** [comment]
Can you gist your schema?

**Comment by sjchmiela** [comment]
Schema:
https://gist.github.com/sjchmiela/319208e1a450ead062c8c644ba5b84e5

Imported types:
https://gist.github.com/sjchmiela/b9df9a178f41d7bc9c28f03d42bbb4ae

**Comment by rcoedo** [comment]
I'm having the same problem with a very simple schema.

```
defmodule Albert.GraphQL.Schema do
  use Absinthe.Schema
  use Absinthe.Relay.Schema

  alias Albert.GraphQL.Resolver
  alias Albert.Model.Domain.Ingredient

  node interface do
    resolve_type fn
      (%Ingredient{}, _) -> :ingredient
      (_, _) -> nil
    end
  end

  node object :ingredient do
    field :name, non_null(:string)
  end

  query do
    field :ingredients, list_of(:ingredient) do
      arg :id, :id
      resolve &Resolver.Ingredient.find/2
    end
  end
end
```

**Comment by benwilson512** [comment]
Weird, I am not having the issue with this smaller schema (haven't tried the original yet). Can you gist the lines from your mix.lock file that have absinthe and absinthe relay?

**Comment by sjchmiela** [comment]
In my case:

```
"absinthe": {:hex, :absinthe, "1.2.0-alpha.1", "77d118421aa0396d4fb062ef0e9abfd869ef7e4773545067a0a80c771e071add", [:mix], []},
"absinthe_relay": {:hex, :absinthe_relay, "1.2.0-alpha.2", "3b839a6cd546f85ae589b8a89cee8d476c808f94ac57c00309633d223546feda", [:mix], [{:absinthe, "1.2.0-alpha.1", [hex: :absinthe, optional: false]}, {:ecto, "~> 1.0 or ~> 2.0", [hex: :ecto, optional: true]}]},
```

**Comment by rcoedo** [comment]
These are the versions I'm currently using
```
     {:absinthe_plug, "~> 1.2.0-alpha0"},
     {:poison, "~> 2.2"},
     {:absinthe_relay, "~> 1.2.0-alpha.2"},
```

**Comment by benwilson512** [comment]
Reproduced, fixing :)

**Comment by sjchmiela** [comment]
Great! What was the problem?

**Comment by benwilson512** [comment]
Hah, we already fixed it, it just didnt' end up in the alpha2.

If you grab `absinthe_relay` `1.2.0-alpha.3` you should be good to go!

**Comment by rcoedo** [comment]
Thanks a lot @benwilson512 🍻
