### ISSUE TITLE
[BUG] Resolve should accept `{:error, _}`

### ISSUE THREAD

**Issue by kiennt** [absinthe-graphql/absinthe#209]
I defined schema with Relay like this

```elixir
defmodule Kipatest.Schema.Account do
  use Absinthe.Schema.Notation
  use Absinthe.Relay.Schema.Notation

  alias Kipatest.Resolver

  object :account_mutations do
    payload field :sign_up do
      input do
        field :name, non_null(:string)
        field :company_name, non_null(:string)
        field :email, non_null(:email)
        field :password, non_null(:string)
        field :timezone, non_null(:string)
      end
      output do
        field :access_token, :string
        field :error, :string
      end
      resolve &Resolver.Account.sign_up/3
    end
  end
end
```

And here is resolver

```elixir
defmodule Kipatest.Resolver.Account do
  alias Kipatest.Services.Account

  def sign_up(parent, args, info) do
    Account.SignUpService.call(args)
  end
end

defmodule Kipatest.Services.Account.SignUpService do
  alias Kipatest.Repo
  alias Kipatest.User

  def call(data) do
    changeset = User.signup_changeset(%User{}, data)
    if changeset.valid? do
      case Repo.insert(changeset) do
        {:ok, %{email: email} = user} ->
          {:ok, %{access_token: ""}}
        _ ->
          {:error, %{error: "some thing wrong"}}
      end
    else
      {:error, %{error: "some thing wrong"}}
    end
  end
end
```

When I ran this query

```elixir
mutation {
  signUp (
    input:{
      email:"hello@gmail.com",
    	password:"wow",
      name:"hello",
      companyName:"hello",
      timezone:"vn",
      clientMutationId: "1"
  	}
  ){
   	accessToken
    error
  }
}
```

When I ran the query twice, it raise an exception

```
[error] #PID<0.365.0> running Kipatest.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /graphiql
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{client_mutation_id: "1", error: "some thing wrong"}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:147: Absinthe.Phase.Document.Execution.Resolution.build_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:135: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:81: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:49: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:26: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:200: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:92: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:59: Absinthe.Plug.call/2
        (kipatest) lib/phoenix/router.ex:261: Kipatest.Router.dispatch/2
        (kipatest) web/router.ex:1: Kipatest.Router.do_call/2
        (kipatest) lib/kipatest/endpoint.ex:1: Kipatest.Endpoint.phoenix_pipeline/1
        (kipatest) lib/plug/debugger.ex:123: Kipatest.Endpoint."call (overridable 3)"/2
        (kipatest) lib/kipatest/endpoint.ex:1: Kipatest.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Currently, I have to make a work around, by change `{:error, %{error: "some thing wrong"}}` to `{:ok, %{error: "some thing wrong"}}`

**Comment by sjchmiela** [comment]
You defined in your schema a “happy payload” containing both `access_token` and `error`. 

```
      output do
        field :access_token, :string
        field :error, :string
      end
```

To fill these fields with data you need to return `{:ok, map}`, as written in [tutorial](http://absinthe-graphql.org/tutorial/query-arguments/).

> Resolve functions are expected to return either {:ok, item} or {:error, binary | [binary, ...]}.

As you can see, you would like to return a `{:error, map}` tuple, which for now isn't supported. To return an error for now you can either return:
```
{:ok, %{error: "some thing wrong"}}  # which in my opinion you shouldn't
                                     # because it's not “ok”
                                     # and Relay (which you use as you wrote)
                                     # would call onSuccess callback
                                     # instead of onFailure
```
or
```
{:error, "something wrong"} # now you can get the error in Relay in onFailure callback
                            # mutation => mutation.getError()
```

**Comment by sjchmiela** [comment]
The feature you're mentioning here and would like to use is still being implemented at the moment: https://github.com/absinthe-graphql/absinthe/issues/196

**Comment by benwilson512** [comment]
I'm a bit confused, why is the `error` field part of your payload? If you want to use graphql errors for that field, then you should not have the error in the payload and instead just return `{:error, "something went wrong"}`

If you DO want to have potential errors in the payload then `{:ok, %{error: "message"}}` is the correct answer, not a work around. the `:ok` or `:error` is exclusively about telling Absinthe whether or not it needs to add something to the top level graphql errors field.

**Comment by bruce** [comment]
Ah, when we talked about this earlier I didn't see the error in the payload there.
