### ISSUE TITLE
Exception when missing parameter

### ISSUE THREAD

**Issue by fazibear** [absinthe-graphql/absinthe#250]
This exception occurs when parameter not exists in the schema.

In this example, `token` parameter not exists.

Example:

```js
query {
  search(query: "test") {
   id 
   user {
      followed(token: "xxx")
    }
  }
}

```

```Request: POST /graphql
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.name/0 is undefined or private
        nil.name()
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:35: anonymous fn/4 in Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:31: anonymous fn/3 in Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:29: Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (absinthe) lib/absinthe/blueprint/transform.ex:13: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2```

**Comment by benwilson512** [comment]
Hey what version of absinthe are you on?

**Comment by fazibear** [comment]
`1.2.3`

**Comment by benwilson512** [comment]
Weird, I'm having trouble reproducing. Are you able to create a minimal schema and query that exhibits this behaviour?

**Comment by benwilson512** [comment]
Can you try this on master?

**Comment by fazibear** [comment]
No, won't work on master. This is exact query: 

```
query {
  discovery {
    videos(forItem: "random") {
      id
      liked(token: "whatever")
    }
  }
}
```

this one works well:

```
query {
  discovery {
    videos(forItem: "random") {
      id
      liked
    }
  }
}
```

and exception:

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.name/0 is undefined or private
        nil.name()
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:35: anonymous fn/4 in Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:31: anonymous fn/3 in Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/validation/known_argument_names.ex:29: Absinthe.Phase.Document.Validation.KnownArgumentNames.handle_node/2
        (absinthe) lib/absinthe/blueprint/transform.ex:13: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2

```

**Comment by benwilson512** [comment]
can you show me the field definition for `liked` ?

**Comment by fazibear** [comment]
```
    field :liked, :boolean do
      resolve fn(_, %{context: %{current_user: current_user}, source: video}) ->
        batch({Preload, :liked, current_user}, video.id, fn(likes) ->
          {
            :ok,
            Enum.member?(likes, video.id)
          }
        end)
      end
    end
```

**Comment by benwilson512** [comment]
aha! Reproduced. it only happens when the parent field is a list value. will get a fix out.

**Comment by fazibear** [comment]
Thanks :1st_place_medal:

**Comment by benwilson512** [comment]
Can you try again on master?
