### ISSUE TITLE
Error when `__typename` supplied in variables

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#342]
While `__typename` shouldn't be in variables it also shouldn't blow up.

```
3] 
 ```[error] #PID<0.763.0> running ResponseAutomator.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/graphql
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.identifier/0 is undefined or private
        nil.identifier()
        (absinthe) lib/absinthe/phase/document/arguments/data.ex:52: anonymous fn/1 in Absinthe.Phase.Document.Arguments.Data.handle_node/1
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/arguments/data.ex:52: Absinthe.Phase.Document.Arguments.Data.handle_node/1
        (absinthe) lib/absinthe/blueprint/transform.ex:39: anonymous fn/3 in Absinthe.Blueprint.Transform.postwalk/2
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:123: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:113: Absinthe.Blueprint.Transform.node_with_children/5
        (absinthe) lib/absinthe/blueprint/transform.ex:123: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:113: Absinthe.Blueprint.Transform.node_with_children/5
        (absinthe) lib/absinthe/blueprint/transform.ex:123: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:113: Absinthe.Blueprint.Transform.node_with_children/5
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:123: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (absinthe) lib/absinthe/blueprint/transform.ex:113: Absinthe.Blueprint.Transform.node_with_children/5```
```

**Comment by benwilson512** [comment]
Fixed in master!

**Comment by arjan** [comment]
Life saver.. :)
