### ISSUE TITLE
import_field does not work with subscriptions

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#375]
When using `import_fields` with subscriptions, I ended up with the following error:

```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1832: Enum.reduce/3
        (stdlib) lists.erl:1263: :lists.foldl/3
        (absinthe) lib/absinthe/subscription.ex:79: Absinthe.Subscription.get_subscription_fields/1
        (absinthe) lib/absinthe/subscription.ex:65: Absinthe.Subscription.publish/3
        (absinthe) lib/absinthe/subscription.ex:138: Absinthe.Subscription.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:194: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:164: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:150: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:57: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:25: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:248: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:274: Absinthe.Plug.run_query/3
        (absinthe_plug) lib/absinthe/plug.ex:202: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:155: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
```

This is closely related with #374

**Comment by benwilson512** [comment]
Should be fixed in master too.
