### ISSUE TITLE
Subscription name collision

### ISSUE THREAD

**Issue by binaryseed** [absinthe-graphql/absinthe#393]
Hi there, just playing around with subscriptions, and ran into a bug.. 

We have an object named `subscription` in our schema, and we get a strange error in `1.4.0-rc.0`

Changing the object name clears it up, so there's some kind of name collision happening!

```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{account_id: 1, ...}. This protocol is implemented for: Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
        (absinthe) lib/absinthe/phase/document/result.ex:53: Absinthe.Phase.Document.Result.data/2
        (absinthe) lib/absinthe/phase/document/result.ex:79: Absinthe.Phase.Document.Result.field_data/3
        (absinthe) lib/absinthe/phase/document/result.ex:69: Absinthe.Phase.Document.Result.list_data/3
        (absinthe) lib/absinthe/phase/document/result.ex:79: Absinthe.Phase.Document.Result.field_data/3
        (absinthe) lib/absinthe/phase/document/result.ex:20: Absinthe.Phase.Document.Result.process/1
        (absinthe) lib/absinthe/phase/document/result.ex:12: Absinthe.Phase.Document.Result.run/2
        (absinthe) lib/absinthe/pipeline.ex:249: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:291: Absinthe.Plug.run_query/3
        (absinthe_plug) lib/absinthe/plug.ex:219: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:155: Absinthe.Plug.call/2
```

Thanks!

**Comment by benwilson512** [comment]
@binaryseed `:subscription` is a reserved object name, unfortunately if you have an object by that name you'll need to change it.

**Comment by binaryseed** [comment]
I made an attempt to raise a better error, but I can't properly differentiate the case of `object :subscription` and `subscription do`...

**Comment by benwilson512** [comment]
Handled by #396
