### ISSUE TITLE
Attempt to programmatically get enum values fails with matcherror

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe#427]
I am trying to define a GraphQL enum that gets its values from a function.

The use case is that I want one source of truth for the possible values of a field, we validate in an Ecto model and store the list of possible values there. I'd like to put that list into an enum.

I tried this:

```elixir
enum :agency_confidence, values: PropertiesDB.Deal.agency_confidences
```

Where `PropertiesDB.Deal.agency_confidences` returns a list of atoms.

But I get this error:

```
== Compilation error in file lib/eggl/schema/types/nest_deal.ex ==
** (FunctionClauseError) no function clause matching in Absinthe.Type.Enum.Value.build/1

    The following arguments were given to Absinthe.Type.Enum.Value.build/1:

        # 1
        {{:., [line: 7], [PropertiesDB.Deal, :agency_confidences]}, [line: 7], []}

    Attempted function clauses (showing 1 out of 1):

        def build(raw_values) when is_list(raw_values)

    lib/absinthe/type/enum/value.ex:31: Absinthe.Type.Enum.Value.build/1
    lib/absinthe/type/enum.ex:93: Absinthe.Type.Enum.build/1
    lib/absinthe/schema/notation/writer.ex:91: Absinthe.Schema.Notation.Writer.type_functions/1
    lib/absinthe/schema/notation/writer.ex:222: anonymous fn/2 in Absinthe.Schema.Notation.Writer.update_type_functions/3
    (elixir) lib/map.ex:727: Map.update!/3
    lib/absinthe/schema/notation/writer.ex:203: Absinthe.Schema.Notation.Writer.do_build_info/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Absinthe.Schema.Notation.Writer.__before_compile__/1
```

**Comment by benwilson512** [comment]
Hey @samphilipd, at the moment only macros can be used for this purpose, since we need to do compile time work on the values. Can you try having
```
defmacro agency_confidences do
  quote do
    [:foo, :bar, :baz]
  end
end
```

**Comment by samphilipd** [comment]
Hi Ben thanks this is great. I was able to achieve what I wanted by doing this:

```elixir
# In the model
defmacro agency_confidences, do: @agency_confidences

# In the types listing
require PropertiesDB.Deal
enum :agency_confidence, values: PropertiesDB.Deal.agency_confidences
```
