### ISSUE TITLE
graphiql fails when upgrading to  absinthe 1.4.12

### ISSUE THREAD

**Issue by thanos** [absinthe-graphql/absinthe#563]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.5 (compiled with OTP 20)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.4.12 (Hex package) (mix)
  locked at 1.4.12 (absinthe) 50e7a700
* absinthe_plug 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (absinthe_plug) f93db435
* absinthe_phoenix 1.4.2 (Hex package) (mix)
  locked at 1.4.2 (absinthe_phoenix) cb84c81b
* absinthe_ecto 0.1.3 (https://github.com/absinthe-graphql/absinthe_ecto.git) (mix)
```

### Expected behavior
absinthe
`http://localhost:4000/graphiql/`  works under when served with the following:
```
* absinthe (Hex package) (mix)
  locked at 1.3.2 (absinthe) 1d16ee5c
* absinthe_plug (Hex package) (mix)
  locked at 1.3.1 (absinthe_plug) e97c9faa
* absinthe_ecto (https://github.com/absinthe-graphql/absinthe_ecto.git) (mix)
```

Upgrade to:
```
* absinthe 1.4.12 (Hex package) (mix)
  locked at 1.4.12 (absinthe) 50e7a700
* absinthe_plug 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (absinthe_plug) f93db435
* absinthe_phoenix 1.4.2 (Hex package) (mix)
  locked at 1.4.2 (absinthe_phoenix) cb84c81b
* absinthe_ecto 0.1.3 (https://github.com/absinthe-graphql/absinthe_ecto.git) (mix)
```

**BUT WITHOUT RESTARTING  the server** `graphiql` still works fine. 

Restart and I get below

### Actual behavior

```
[info] GET /graphiql
[info] Sent 500 in 154ms
[error] #PID<0.426.0> running UiBackendWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /graphiql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Absinthe.Plug.GraphiQL.find_socket_path/2
        (absinthe_plug) lib/absinthe/plug/graphiql.ex:300: anonymous fn({"/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket, [], [{["phoenix", "live_reload", "socket", "websocket"], {:websocket, Phoenix.LiveReloader.Socket, [serializer: [{Phoenix.Socket.V1.JSONSerializer, "~> 1.0.0"}, {Phoenix.Socket.V2.JSONSerializer, "~> 2.0.0"}], timeout: 60000, transport_log: false, compress: false]}}]}) in Absinthe.Plug.GraphiQL.find_socket_path/2
        (elixir) lib/enum.ex:2886: Enum.find_list/3
        (absinthe_plug) lib/absinthe/plug/graphiql.ex:300: Absinthe.Plug.GraphiQL.find_socket_path/2
        (absinthe_plug) lib/absinthe/plug/graphiql.ex:413: Absinthe.Plug.GraphiQL.normalize_socket_url/2
        (absinthe_plug) lib/absinthe/plug/graphiql.ex:199: Absinthe.Plug.GraphiQL.do_call/2
        (phoenix) lib/phoenix/router/route.ex:39: Phoenix.Router.Route.call/2
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (ui_backend) lib/ui_backend_web/endpoint.ex:1: UiBackendWeb.Endpoint.plug_builder_call/2
        (ui_backend) lib/plug/debugger.ex:102: UiBackendWeb.Endpoint."call (overridable 3)"/2
        (ui_backend) lib/ui_backend_web/endpoint.ex:1: UiBackendWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/thanos/Projects/ui_backend/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

```
FunctionClauseError at GET /graphiql
no function clause matching in anonymous fn/1 in Absinthe.Plug.GraphiQL.find_socket_path/2
```

```
lib/absinthe/plug/graphiql.ex
295  defp select_mode(request), do: {:process, request}
296
297  defp find_socket_path(conn, socket) do
298    if endpoint = conn.private[:phoenix_endpoint] do
299      endpoint.__sockets__
300      |> Enum.find(fn {_, module} ->
301        module == socket
302      end)
303      |> case do
304        {path, _} -> {:ok, path}
305        _ -> :error
```

#### router.ex

```
defmodule UiBackendWeb.Router do
  use UiBackendWeb, :router


  pipeline :auth do
    plug UiBackend.AccountManager.Pipeline
  end
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end



  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UiBackendWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :index
    # get "/security", PageController, :security
    post "/", PageController, :login
    post "/logout", PageController, :logout
  end



  # Other scopes may use custom stacks.
  scope "/api", UiBackendWeb do
    pipe_through :api
  end

  forward "/graph", Absinthe.Plug, schema: UiBackendWeb.Graphql.Schema
  forward "/graphiql", Absinthe.Plug.GraphiQL, schema: UiBackendWeb.Graphql.Schema, interface: :simple






end

```
#### endpoint.ex

```
defmodule UiBackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ui_backend

  socket "/socket", UiBackendWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :ui_backend, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt mkh.html cards static)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_ui_backend_key",
    signing_salt: "pQWIBgPc"

  plug CORSPlug
  plug UiBackendWeb.Router

  @doc """
  Callback invoked for dynamically configuring the endpoint.

  It receives the endpoint configuration and checks if
  configuration should be loaded from the system environment.
  """
  def init(_key, config) do
    if config[:load_from_system_env] do
      port = System.get_env("PORT") || raise "expected the PORT environment variable to be set"
      {:ok, Keyword.put(config, :http, [:inet6, port: port])}
    else
      {:ok, config}
    end
  end
end
```

Many Thanks for this great framework

**Comment by thanos** [comment]
I'm moving this to `absinthe_plug` but I do feel that the ticket should maybe be under this project as `graphiql` is a key tool of this framework.

**Comment by benwilson512** [comment]
Hey @thanos  thanks for the issue. I don't think it makes sense to track it in two places, and from a code perspective this looks exclusively like an issue with how absinthe_plug interacts with phoenix.

**Comment by thanos** [comment]
I agree. Just for the record
`{:absinthe_plug, git: "https://github.com/absinthe-graphql/absinthe_plug.git", override: true},`

fixes things
