### ISSUE TITLE
Error when enforcing keys with Absinthe middleware

### ISSUE THREAD

**Issue by samsondav** [absinthe-graphql/absinthe#618]
We are using a custom middleware to get stricter checking of keys:

```
defmodule Eggl.Schema.Middleware.MapFetch do
  @moduledoc """
  A stricter default resolver.
  """

  @behaviour Absinthe.Middleware

  @spec call(%{source: map(), state: any(), value: any()}, any()) :: %{
          source: map(),
          state: :resolved,
          value: any()
        }
  def call(%{source: source} = res, key) do
    %{res | state: :resolved, value: Map.fetch!(source, key)}
  end
end
```

But we see the following error when introspecting the schema:

```
Mix.Tasks.Absinthe.Schema.Json.run([schema_file])
```

```
** (KeyError) key :name not found in: %Absinthe.Type.NonNull{of_type: :date}
     stacktrace:
       (stdlib) :maps.get(:name, %Absinthe.Type.NonNull{of_type: :date})
       (eggl) lib/eggl/schema/middleware/map_fetch_middleware.ex:14: Eggl.Schema.Middleware.MapFetch.call/2
       (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1```
```

In case it helps, we are including the middleware like this:

```
def middleware(middlewares, field, object = %{identifier: :mutation}) do
        (middlewares ++ [Eggl.Schema.Middleware.MutationErrors])
        |> apply_common_middlewares(field, object)
      end

      def middleware(middlewares, field, object) do
        middlewares
        |> apply_common_middlewares(field, object)
      end

      defp apply_common_middlewares(middlewares, field, object) do
        middlewares
        |> EgglCommon.AbsintheMetrics.Instrumenter.instrument(field, object)
        |> Absinthe.Schema.replace_default(
          {Eggl.Schema.Middleware.MapFetch, field.identifier},
          field,
          object
        )
      end
```

**Comment by halostatue** [comment]
You may be overaggressively replacing `Map.get/2` with `Map.fetch!/2` on types that are fundamentally not objects. My guess is you have a custom scalar of type `:date` and you’re trying to get the `name` of the type, but scalars don’t have names as such. If you look at 
_Craft GraphQL APIs in Elixir with Absinthe_, chapter 7 (“Resolution Middleware”), page 136, the example there clearly looks for an identifier:

```elixir
def middleware(middleware, field, %{identifier: :allergy_info} = object) do
  new_middleware = {Absinthe.Middleware.MapGet, to_string(field.identifier)}
  middleware |> Absinthe.Schema.replace_default(new_middleware, field, object)
end
```

The use of `Map.fetch!/2` here seems to be misguided in any case, as any type that is not non-null should be able to return `nil` values per the GraphQL spec. With your use of `Map.fetch!`, you’re going to end up with `KeyError` stack traces all over the place.

**Comment by halostatue** [comment]
Related to #565 and absinthe-graphql/absinthe_plug#159, so what you’re doing should be working—although I maintain that the use of `Map.fetch!/2` is misguided.

**Comment by tfwright** [comment]
I think I ran into this when I started getting a very mysterious error in the graphiql UI:

```
TypeError: Cannot read property 'reduce' of null
    at keyMap (https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:18:19182)
    at buildClientSchema (https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:28791)
    at https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:14:12777
```

Removing the middleware fixed it.

**Comment by benwilson512** [comment]
I agree that this is probably not advisable. If an example can be provided that should work but does not I'm happy to reopen.
