### ISSUE TITLE
Error providing InputObjects values as query document variables

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#65]
Issue originally found in #62, and occurs during value coercion when building the variables for the execution context.

```
** (MatchError) no match of right hand side value: %Absinthe.Type.InputObject{__reference__: %{identifier: :create_user_inp
ut, location: %{file: "/web/graph/schema/type/user.ex", line: 22}, module: Graph.Schema.Type.U
ser}, description: nil, fields: %{email: %Absinthe.Type.Field{__reference__: %{identifier: :email, location: %{file: "/web/graph/schema/type/user.ex", line: 23}, module: Graph.Schema.Type.User}, args: %{}, default_value:
nil, deprecation: nil, description: nil, name: "email", resolve: nil, type: %Absinthe.Type.NonNull{of_type: :string}}, name: %A
bsinthe.Type.Field{__reference__: %{identifier: :name, location: %{file: "/web/graph/schema/type/user.e
x", line: 24}, module: Graph.Schema.Type.User}, args: %{}, default_value: nil, deprecation: nil, description: nil, nam
e: "name", resolve: nil, type: %Absinthe.Type.NonNull{of_type: :string}}}, name: "CreateUserInput"}
        (absinthe) lib/absinthe/execution/variables.ex:95: Absinthe.Execution.Variables.coerce/2
        (absinthe) lib/absinthe/execution/variables.ex:66: Absinthe.Execution.Variables.valid/4
```

It looks like we need to handle this case specifically in `Variables.build` and `Arguments.build`.

**Comment by benwilson512** [comment]
@dre1080 just wanted to give you an update. We've been looking through this and this bug has uncovered a slightly more general problem with handling complex input types. I'll be working on an improved implementation tomorrow, as we need this functionality ourselves too.

We hope to have it fixed very soon.

**Comment by dre1080** [comment]
@benwilson512 thanks. Looking forward to seeing this fixed

**Comment by benwilson512** [comment]
@dre1080 hey! can you try now against master? The latest merge should have fixed this issue.

**Comment by dre1080** [comment]
@benwilson512 it seems like its working now :smile: 
All that's left is Relay integration for `clientMutationId`

**Comment by benwilson512** [comment]
Yup we've got a whole library in the works for relay support, https://github.com/absinthe-graphql/absinthe_relay

**Comment by dre1080** [comment]
I am however getting this response when testing mutations, 

```js
{"errors":[{"message":"Variable `input_0.clientMutationId': Not present in schema","locations":[{"line":1,"column":0}]},{"message":"Variable `input_0.clientMutationId' (String): Not provided","locations":[{"line":1,"column":0}]}],"data":{}}
```

Same schema as before but added `field :client_mutation_id, non_null(:string)`

**Comment by benwilson512** [comment]
Can you show an example test case? What's a minimal schema, variable value, and document needed to reproduce?

**Comment by dre1080** [comment]
Here's the schema I'm testing with: 

```
defmodule API.Graph.Schema do
  use Absinthe.Schema

  alias API.Resolver

  object :user do
    field :id, :id
    field :email, :string
    field :name, :string
  end

  object :create_user_payload, name: "CreateUserPayload" do
    field :user, :user
    field :client_mutation_id, non_null(:string)
  end

  input_object :create_user_input, name: "CreateUserInput" do
    field :email, non_null(:string)
    field :name, non_null(:string)
    field :client_mutation_id, non_null(:string)
  end

  mutation do
    @desc "Create a user"
    field :create_user, type: :create_user_payload do
      arg :input, non_null(:create_user_input)

      resolve &Resolver.User.create/2
    end
  end

  query do
    field :viewer, :user do
      resolve &Resolver.User.current/2
    end
  end
end
```

This is the request payload:

```
{
  query: "mutation createUserMutation($input_0:CreateUserInput){createUser(input:$input_0){clientMutationId}}"
  variables: {input_0: {clientMutationId: "0", email: "john@example.com", name: "John"}}
}
```

**Comment by benwilson512** [comment]
Ah hm maybe variables aren't run through the adapters? Hold up let me see if I can confirm.

**Comment by benwilson512** [comment]
Yeah it's definitely that adapters aren't being used to coerce inner
variable values. I'll patch that in the morning, good catch thanks!

**Comment by benwilson512** [comment]
Hey give it a shot now.

**Comment by bruce** [comment]
@benwilson512 Closing this because I think this is handled. Reopen if necessary.
