### ISSUE TITLE
Decorate scalar types via import_sdl

### ISSUE THREAD

**Issue by maennchen** [absinthe-graphql/absinthe#702]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 21)
```

* Absinthe version (mix deps | grep absinthe):
```
* absinthe 1.5.0-alpha.4 (Hex package) (mix)
  locked at 1.5.0-alpha.4 (absinthe) fa6dbd49
* absinthe_plug 1.4.6 (Hex package) (mix)
  locked at 1.4.6 (absinthe_plug) ac5d2d3d
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e
```

* Client Framework and version (Relay, Apollo, etc):
None currently

### Expected behavior

No error

### Actual behavior

```
== Compilation error in file lib/acme_api/schema.ex ==
** (FunctionClauseError) no function clause matching in Absinthe.Phase.Schema.Decorate.apply_decoration/2

    The following arguments were given to Absinthe.Phase.Schema.Decorate.apply_decoration/2:

        # 1
        %Absinthe.Blueprint.Schema.ScalarTypeDefinition{__private__: [], __reference__: %{location: %{file: "priv/schema.gql", line: 10}, module: AcmeApi.Schema}, description: nil, directives: [], errors: [], flags: %{}, identifier: :xyz, module: AcmeApi.Schema, name: "XYZ", parse: nil, serialize: nil, source_location: %Absinthe.Blueprint.SourceLocation{column: 8, line: 10}}

        # 2
        {:serialize, #Function<0.91803757/1 in AcmeApi.Schema.decorations/2>}

    Attempted function clauses (showing 2 out of 2):

        def apply_decoration(node, {:description, text})
        def apply_decoration(node, {:resolve, resolver})

    (absinthe) lib/absinthe/phase/schema/decorate.ex:78: Absinthe.Phase.Schema.Decorate.apply_decoration/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe) lib/absinthe/phase/schema/decorate.ex:44: Absinthe.Phase.Schema.Decorate.handle_node/4
    (absinthe) lib/absinthe/phase/schema/decorate.ex:56: anonymous fn/5 in Absinthe.Phase.Schema.Decorate.set_children/4
    (absinthe) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (absinthe) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
    (absinthe) lib/absinthe/phase/schema/decorate.ex:56: anonymous fn/5 in Absinthe.Phase.Schema.Decorate.set_children/4
    (absinthe) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe) lib/absinthe/blueprint/transform.ex:145: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (absinthe) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
```

### Relevant Schema/Middleware Code

```gql
scalar XYZ
```

```elixir
import_sdl path: "priv/schema.gql"

def decorations(%Schema.ScalarTypeDefinition{identifier: :xyz} = node, ancestors) do
  {:serialize, &__MODULE__.serialize_xyz/1}
end
```

### Proposed Fix

`Absinthe.Phase.Schema.Decorate`

```elixir
def apply_decoration(node, {:serialize, fun}) do
  %{node | serialize: fun}
end
def apply_decoration(node, {:parse, fun}) do
  %{node | parse: fun}
end
```

**Comment by maennchen** [comment]
PS: Maybe this is the wrong way to do it, I just figured that this is the way it's supposed to work.

**Comment by maennchen** [comment]
Just guessing: I think this applies as well for `resolve_type` / `is_type_of` for interfaces.
