### ISSUE TITLE
dataloader/2 fails

### ISSUE THREAD

**Issue by archseer** [absinthe-graphql/absinthe#720]
I was trying to use `field :some, resolve: dataloader(MyModule, use_parent: true)` (since #556 still isn't resolved). It seems to fail because it expects a function as the second argument?

```
 ** (RuntimeError) Invalid: {[use_parent: true], %{}}
%Data.MyModel{...}

The batch key must either be a schema module, or an association name.

        (dataloader) lib/dataloader/ecto.ex:446: Dataloader.Source.Dataloader.Ecto.get_keys/2
        (dataloader) lib/dataloader/ecto.ex:327: Dataloader.Source.Dataloader.Ecto.fetch/3
        (dataloader) lib/dataloader/ecto.ex:367: Dataloader.Source.Dataloader.Ecto.load/3
        (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
        (dataloader) lib/dataloader.ex:128: Dataloader.load_many/4
        (absinthe) lib/absinthe/resolution/helpers.ex:289: Absinthe.Resolution.Helpers.do_dataloader/6
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:229: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:184: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:169: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:279: Absinthe.Phase.Document.Execution.Resolution.build_result/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:169: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:114: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:103: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:279: Absinthe.Phase.Document.Execution.Resolution.build_result/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:169: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:279: Absinthe.Phase.Document.Execution.Resolution.build_result/3
```

**Comment by maartenvanvliet** [comment]
`use_parent: true` is part of a keyword list that is in the third argument of dataloader/3. 

If you want dataloader to use a relation, you have to specify its name again in the second argument. 
`field :posts, resolve: dataloader(MyModule, :posts, use_parent: true)`

When you use dataloader with one argument, the relationship is inferred from the field name
`field :posts, resolve: dataloader(MyModule)`

I think this can be closed
