### ISSUE TITLE
Bad operation name can result in exception

### ISSUE THREAD

**Issue by xxhenglyxx** [absinthe-graphql/absinthe#726]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* Absinthe version (mix deps | grep absinthe):
```
* absinthe 1.4.16 (Hex package) (mix)
  locked at 1.4.16 (absinthe) 0933e4d9
* absinthe_ecto 0.1.3 (Hex package) (mix)
  locked at 0.1.3 (absinthe_ecto) 420b6812
* absinthe_plug 1.4.7 (Hex package) (mix)
  locked at 1.4.7 (absinthe_plug) 939b6b9e
* absinthe_phoenix 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (absinthe_phoenix) af3b7b44
```
* Client Framework and version (Relay, Apollo, etc): `graphql_flutter: 1.0.1-beta.7`

### Expected behavior

No error and log out any result from an operation(query or mutation) on the client side(flutter)

### Actual behavior

```
[error] #PID<0.3584.0> running AppServerWeb.Endpoint (connection #PID<0.3583.0>, stream id 1) terminated
Server: 10.0.2.2:4000 (http)
Request: POST /api/graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Absinthe.Phase.Document.Result.data/2
        (absinthe) lib/absinthe/phase/document/result.ex:50: Absinthe.Phase.Document.Result.data(nil, [])
        (absinthe) lib/absinthe/phase/document/result.ex:19: Absinthe.Phase.Document.Result.process/1
        (absinthe) lib/absinthe/phase/document/result.ex:11: Absinthe.Phase.Document.Result.run/2
        (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:39: Phoenix.Router.Route.call/2
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (app_server) lib/app_server_web/endpoint.ex:1: AppServerWeb.Endpoint.plug_builder_call/2
        (app_server) lib/plug/debugger.ex:122: AppServerWeb.Endpoint."call (overridable 3)"/2
        (app_server) lib/app_server_web/endpoint.ex:1: AppServerWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
```

### Relevant Schema/Middleware Code

All api is working on graphql playground, except when requesting them from `flutter`. Could anyone please explain me why the problem and how to debug that? thanks very much beforehand.

**Comment by benwilson512** [comment]
Interesting, can you set the log level to info so that Absinthe will print the query body and variables? I can't really debug much without seeing the input.

**Comment by xxhenglyxx** [comment]
yes @benwilson512 , here is the output:

```
Compiling 4 files (.ex)
[info] Running AppServerWeb.Endpoint with cowboy 2.6.3 at 0.0.0.0:4000 (http)
[info] Access AppServerWeb.Endpoint at http://localhost:4000
[info] POST /api/graphql
[debug] ABSINTHE schema=AppServerWeb.Schema variables=%{}
---
mutation {
    signIn {
      token
      refreshToken
      username
      __typename
    }
  }
---
[info] Sent 500 in 220ms
[error] #PID<0.563.0> running AppServerWeb.Endpoint (connection #PID<0.562.0>, stream id 1) terminated
Server: 10.0.2.2:4000 (http)
Request: POST /api/graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Absinthe.Phase.Document.Result.data/2
        (absinthe) lib/absinthe/phase/document/result.ex:50: Absinthe.Phase.Document.Result.data(nil, [])
        (absinthe) lib/absinthe/phase/document/result.ex:19: Absinthe.Phase.Document.Result.process/1
        (absinthe) lib/absinthe/phase/document/result.ex:11: Absinthe.Phase.Document.Result.run/2
        (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:39: Phoenix.Router.Route.call/2
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (app_server) lib/app_server_web/endpoint.ex:1: AppServerWeb.Endpoint.plug_builder_call/2
        (app_server) lib/plug/debugger.ex:122: AppServerWeb.Endpoint."call (overridable 3)"/2
        (app_server) lib/app_server_web/endpoint.ex:1: AppServerWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/xxx/projects/xxx/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
# ends, nothing more
```

**Comment by benwilson512** [comment]
OK cool, can you show the resolver code, and ideally `|> IO.inspect` the value you're returning from the resolver?

**Comment by xxhenglyxx** [comment]
I tried logging anything inside the resolver but the request does not trigger the resolver but the error instead.

Here is the schema and resolver

```
defmodule AppServerWeb.Typedefs.Accounts.User do
  alias AppServerWeb.Middlewares
  alias AppServerWeb.Resolvers

  object :user_session do
    field :token, :string, complexity: 7
    field :refresh_token, :string, complexity: 7
    field :username, :string, complexity: 6
  end

  object :user_mutations do
    field :sign_in, :user_session do
      middleware Middlewares.Resolvers.RejectAlreadyLogin

      resolve &Resolvers.Accounts.User.sign_in/3
    end
  end
end
```

```
defmodule AppServerWeb.Resolvers.Accounts.User do
  def sign_in(_, _, %{context: %{openid_token: "" <> id_token}}) do
    IO.puts "++++++++"
    id_token
    |> OpenId.extract_claims()
    |> create_user_access_tokens()
    |> IO.inspect()
  end
  def sign_in(_, _, _), do: {:ok, %{token: nil, refresh_token: nil, username: nil}}
end
```

I also logs out the `conn` on the putting user context plug

```
defmodule AppServerWeb.Plugs.Context do
  @behaviour Plug
  
  import Plug.Conn
  
  alias AppServer.Accounts

  def init(opts), do: opts

  def call(conn, _opts) do
    conn
    |> extract_tokens()
    |> verify_and_decode_token()
    |> put_user_context(conn)
    |> IO.inspect()
  end

  ...
end
```

Here is the output:

```
[info] POST /api/graphql
%Plug.Conn{
  adapter: {Plug.Cowboy.Conn, :...},
  assigns: %{},
  before_send: [#Function<1.112466771/1 in Plug.Logger.call/2>,
   #Function<0.6186620/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>],
  body_params: %{
    "operationName" => "UNNAMED/530188889",
    "query" => "  mutation {\n    signIn {\n      token\n      refreshToken\n      username\n      __typename\n    }\n  }\n  ",
    "variables" => %{}
  },
  cookies: %Plug.Conn.Unfetched{aspect: :cookies},
  halted: false,
  host: "10.0.2.2",
  method: "POST",
  owner: #PID<0.568.0>,
  params: %{
    "operationName" => "UNNAMED/530188889",
    "query" => "  mutation {\n    signIn {\n      token\n      refreshToken\n      username\n      __typename\n    }\n  }\n  ",
    "variables" => %{}
  },
  path_info: ["api", "graphql"],
  path_params: %{},
  port: 4000,
  private: %{
    AppServerWeb.Router => {[],
     %{Absinthe.Plug => ["graphql"], Absinthe.Plug.GraphiQL => ["graphiql"]}},
    :absinthe => %{
      context: %{
        openid_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjVkODg3ZjI2Y2UzMjU3N2M0YjVhOGExZTFhNTJlMTlkMzAxZjgxODEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4NjczMzk4NzU4NjAtY2k5M3A2cHZpY2txbGJwYmRtMzZjamlxcnQzNTQzNmsuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4NjczMzk4NzU4NjAtMHQyNTB2OTc3dWZnZG05amxkaHFoOGc2bDg5cmNuMXUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTc1MTc2ODA1OTI4Mzc3OTMxNzEiLCJlbWFpbCI6Imx5aGVuZzZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJIZW5nIEx5IiwicGljdHVyZSI6Imh0dHBzOi8vbGg2Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tcjZHYUNCYnVTa0kvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQUNIaTNyZFBQMVdtXy1GLTdobHc1NUpXQkNqTFV1eDhQZy9zOTYtYy9waG90by5qcGciLCJnaXZlbl9uYW1lIjoiSGVuZyIsImZhbWlseV9uYW1lIjoiTHkiLCJsb2NhbGUiOiJlbiIsImlhdCI6MTU1NzEwNTU3MywiZXhwIjoxNTU3MTA5MTczfQ.j9trMfv0oQVaFuNEsDCnilw92z_qCvxsoP9PuZm-k_U3zWiWqyXy_ZC2ep9Fj9cDk3_qyv3sqJDBcygB9ZvKULtE3pBZO9bLRO4aR90Z5-04x59LqEQmeMJ60avfG9JRo9nIV3NrcquXZ4laZTBeUomIKSyjRr8PGiOKurr0_5XuojEd0LYfDKTVjwu-Gd4uucGWqmd67QcbSvaALcmD17u1qesAoeWwXbnWJKcMWDD2v2YC0s6rh-UUyZ8TU-DGD409GqGzb0C1mu3XlFwIXyRkTVos1W8RlU577mbyJrW9C1kN7d87sZc7fty0erEWwIoNARgiKfiQrCh_cHwRkQ"
      }
    },
    :phoenix_endpoint => AppServerWeb.Endpoint,
    :phoenix_format => "json",
    :phoenix_pipelines => [:api],
    :phoenix_router => AppServerWeb.Router,
    :plug_session_fetch => #Function<1.58261320/1 in Plug.Session.fetch_session/1>
  },
  query_params: %{},
  query_string: "",
  remote_ip: {127, 0, 0, 1},
  req_cookies: %Plug.Conn.Unfetched{aspect: :cookies},
  req_headers: [
    {"accept", "*/*"},
    {"accept-encoding", "gzip"},
    {"content-length", "172"},
    {"content-type", "application/json; charset=utf-8"},
    {"host", "10.0.2.2:4000"},
    {"oid",
     "eyJhbGciOiJSUzI1NiIsImtpZCI6IjVkODg3ZjI2Y2UzMjU3N2M0YjVhOGExZTFhNTJlMTlkMzAxZjgxODEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4NjczMzk4NzU4NjAtY2k5M3A2cHZpY2txbGJwYmRtMzZjamlxcnQzNTQzNmsuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4NjczMzk4NzU4NjAtMHQyNTB2OTc3dWZnZG05amxkaHFoOGc2bDg5cmNuMXUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTc1MTc2ODA1OTI4Mzc3OTMxNzEiLCJlbWFpbCI6Imx5aGVuZzZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJIZW5nIEx5IiwicGljdHVyZSI6Imh0dHBzOi8vbGg2Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tcjZHYUNCYnVTa0kvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQUNIaTNyZFBQMVdtXy1GLTdobHc1NUpXQkNqTFV1eDhQZy9zOTYtYy9waG90by5qcGciLCJnaXZlbl9uYW1lIjoiSGVuZyIsImZhbWlseV9uYW1lIjoiTHkiLCJsb2NhbGUiOiJlbiIsImlhdCI6MTU1NzEwNTU3MywiZXhwIjoxNTU3MTA5MTczfQ.j9trMfv0oQVaFuNEsDCnilw92z_qCvxsoP9PuZm-k_U3zWiWqyXy_ZC2ep9Fj9cDk3_qyv3sqJDBcygB9ZvKULtE3pBZO9bLRO4aR90Z5-04x59LqEQmeMJ60avfG9JRo9nIV3NrcquXZ4laZTBeUomIKSyjRr8PGiOKurr0_5XuojEd0LYfDKTVjwu-Gd4uucGWqmd67QcbSvaALcmD17u1qesAoeWwXbnWJKcMWDD2v2YC0s6rh-UUyZ8TU-DGD409GqGzb0C1mu3XlFwIXyRkTVos1W8RlU577mbyJrW9C1kN7d87sZc7fty0erEWwIoNARgiKfiQrCh_cHwRkQ"},
    {"user-agent", "Dart/2.3 (dart:io)"}
  ],
  request_path: "/api/graphql",
  resp_body: nil,
  resp_cookies: %{},
  resp_headers: [
    {"cache-control", "max-age=0, private, must-revalidate"},
    {"x-request-id", "FZv0JT__t-h-fa8AAAki"},
    {"x-frame-options", "SAMEORIGIN"},
    {"x-xss-protection", "1; mode=block"},
    {"x-content-type-options", "nosniff"},
    {"x-download-options", "noopen"},
    {"x-permitted-cross-domain-policies", "none"},
    {"cross-origin-window-policy", "deny"},
    {"content-type", "application/json; charset=utf-8"}
  ],
  scheme: :http,
  script_name: [],
  secret_key_base: :...,
  state: :unset,
  status: nil
}
[debug] ABSINTHE schema=AppServerWeb.Schema variables=%{}
---
mutation {
    signIn {
      token
      refreshToken
      username
      __typename
    }
  }
---
[info] Sent 500 in 336ms
[error] #PID<0.568.0> running AppServerWeb.Endpoint (connection #PID<0.567.0>, stream id 1) terminated
Server: 10.0.2.2:4000 (http)
Request: POST /api/graphql
** (exit) an exception was raised:
   ... same errror as above
```

**Comment by benwilson512** [comment]
This is very helpful, thanks!

I will definitely look into why Absinthe isn't producing a proper error message here. However I've also figured out why you're getting an error:

```
%{
    "operationName" => "UNNAMED/530188889",
    "query" => "  mutation {\n    signIn {\n      token\n      refreshToken\n      username\n      __typename\n    }\n  }\n  ",
    "variables" => %{}
  }
```

This is invalid. It's specifying an operation name, but that operation name isn't found in the query document.

**Comment by xxhenglyxx** [comment]
@benwilson512 thank you very much, I found the problem now!. So on the client side, the mutation is supposed to be

```
const String signIn =
  '''
  mutation SignIn {
    signIn {
      token
      refreshToken
      username
    }
  }
  ''';
```

But it was

```
const String signIn =
  '''
  mutation {
    signIn {
      token
      refreshToken
      username
    }
  }
  ''';
```

After adding `SignIn` name to it, it works as expected now. I am so sorry for this stupid mistake haha

**Comment by benwilson512** [comment]
Not a problem at all, Absinthe should be able to handle this kind of issue. I'll definitely look into it.
