### ISSUE TITLE
Absinthe.Schema.Notation.put_desc/2 - cannot call get_attribute ....

### ISSUE THREAD

**Issue by darrenclark** [absinthe-graphql/absinthe#740]
If I had to guess, my changes in #738 probably caused this.  Will take a look into it this weekend.  @benwilson512 might be worth reverting it?

```
** (exit) an exception was raised:
    ** (ArgumentError) could not call get_attribute with argument MyApp.Schema.Mutations.MyMutationsFile because the module is already compiled
        (elixir) lib/module.ex:1986: Module.assert_not_compiled!/2
        (elixir) lib/module.ex:1713: Module.get_attribute/3
        (absinthe) lib/absinthe/schema/notation.ex:1536: Absinthe.Schema.Notation.put_desc/2
        (my_app) lib/my_app_web/schema/mutations/my_mutations_file.ex:83: anonymous fn/3 in MyApp.Schema.Mutations.MyMutationsFile.__absinthe_function__/2
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:354: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2
```

**Comment by benwilson512** [comment]
@darrenclark hm, I'd consider doing an `rm -rf _build` and seeing if the problem persists. I'm running on master with our projects at cargosense and not seeing any issues.

**Comment by darrenclark** [comment]
Ohhhhhhh, had an `arg` inside `resolve(....)` 🤦‍♂ i.e.:

```elixir
field(:my_field, :my_result_type) do
  resolve(fn _, _, _ ->
    arg(:do_something, :boolean)
    {:ok, "etc..."}
  end)
end
```

is case worth guarding against in Absinthe?

**Comment by benwilson512** [comment]
Definitely, we haven't yet reproduced all of the schema macro invocation guards (different than schema validity checks). This specific one is actually really tricky since it's being called at a weird time since it's inside the resolver.
