### ISSUE TITLE
Default value with list_of can't take lists

### ISSUE THREAD

**Issue by jawakarD** [absinthe-graphql/absinthe#851]
### Environment

* Elixir version (elixir -v):
    - Elixir 1.9.0 (compiled with Erlang/OTP 20)
* Absinthe version (mix deps | grep absinthe):
```
* absinthe 1.4.16 (Hex package) (mix)
  locked at 1.4.16 (absinthe) 0933e4d9
* absinthe_plug 1.4.7 (Hex package) (mix)
  locked at 1.4.7 (absinthe_plug) 939b6b9e
* absinthe_phoenix 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (absinthe_phoenix) af3b7b44
```

* Client Framework and version (Relay, Apollo, etc): Apollo

### Expected behavior

When opening Graphiql, black result page and docs

### Actual behavior

![image](https://user-images.githubusercontent.com/31589372/72974286-c1be2500-3df4-11ea-8e6d-00628fad47d2.png)
and not docs are loaded, i assume it's because the introspection query is crashed.

```
[error] #PID<0.16854.0> running DockupUiWeb.Endpoint (connection #PID<0.16853.0>, stream id 1) terminated                                                                                                   
Server: localhost:4000 (http)                                                                                                                                                                               
Request: POST /graphql                                                                                                                                                                                      
** (exit) an exception was raised:                                                                                                                                                                          
    ** (UndefinedFunctionError) function nil.name/0 is undefined                                                                                                                                            
        nil.name()                                                                                                                                                                                          
        (absinthe) lib/absinthe/type/built_ins/introspection.ex:282: anonymous fn/2 in Absinthe.Type.BuiltIns.Introspection.__absinthe_type__/1
        (absinthe) lib/absinthe/resolution.ex:206: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:98: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:98: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5

```

### Relevant Schema/Middleware Code
I don't remember which schema would produce this. I ignored this for some time. But when i needed to test something in graphiql this happened again. So, I'm not sure if this can be reproduced 😢

**Comment by benwilson512** [comment]
Hi @jawakarD , this particular error looks like it would happen if you had a field where the type of the field was an enum, but the default value wasn't found as part of the enum. We should do a better job validating that at compile time, maybe we do in 1.5, I'd have to check.

Can you provide any enums you have, and any fields which use those enums?

**Comment by jawakarD** [comment]
Sure.

This is the only field we use enum in 
```elixir
  input_object :deployments_filter do
    @desc "Matching the status of the deployment"
    field :status, type: list_of(:statuses), default_value: [:ready]
  end
```

```elixir
  enum :statuses do
    value :deleted
    value :ready
    value :queued
    value :starting
    value :failed
    value :deleting
  end
```

The introspection query works when i change the default value to 
```elixir
  input_object :deployments_filter do
    @desc "Matching the status of the deployment"
    field :status, type: list_of(:statuses), default_value: :ready
  end
```
But the default value I'm getting is `status: [Statuses] = [READY]` 😕 

Error comes again when I want the default value to be 
```elixir
  input_object :deployments_filter do
    @desc "Matching the status of the deployment"
    field :status, type: list_of(:statuses), default_value: [:deleted, :deleting]
  end
```

**Comment by benwilson512** [comment]
Ah good question, Do you mind if we close this particular issue and make a new one about that specific question?

**Comment by jawakarD** [comment]
Sure, no problem 🙂

**Comment by jawakarD** [comment]
Even though **graphiql** docs shows as `status: [Statuses] = [READY]` for the field `status` when using 
```elixir
  input_object :deployments_filter do
    @desc "Matching the status of the deployment"
    field :status, type: list_of(:statuses), default_value: :ready
  end
```
The resolver still receive `%{status: :ready}` when i pattern match like this, program crashes.
```elixir
%{status: statuses}, acc ->
    statuses = Enum.map(statuses, &to_string/1)
    from d in acc, where: d.status in ^statuses
```

When I have the field enum uses as:
```elixir
  input_object :deployments_filter do
    @desc "Matching the status of the deployment"
    field :status, type: list_of(:statuses), default_value: [:ready]
  end
```
The query I do manually, works fine, but the introspection query fails.

I'll leave the issue closed, would love to hear the workaround/solution 🙂

**Comment by benwilson512** [comment]
Well, I was gonna suggest we make another issue, but it's fine I'll just reopen this and rename it to focus on the root issue.

**Comment by binaryseed** [comment]
Have you tried this on 1.5? I believe I fixed this with https://github.com/absinthe-graphql/absinthe/pull/792
