### ISSUE TITLE
Running validation-only pipeline barfs on good data.

### ISSUE THREAD

**Issue by ekobi** [absinthe-graphql/absinthe#852]
This is an issue I reported on the Elixir forum, for which @benwilson512 provided a workaround. Wondering if either
- `Absinthe.Pipeline.run()` could handle applying the workaround automatically;

or, alternatively
- `Absinthe.Pipeline` could provide a `for_document_validation()` function that builds a suitably patched input for `run()`

If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): Elixir 1.9.2 (compiled with Erlang/OTP 22)
* Absinthe version (mix deps | grep absinthe):
  - absinthe 1.4.16 (Hex package) (mix)
     locked at 1.4.16 (absinthe) 0933e4d9
  - absinthe_plug 1.4.7 (Hex package) (mix)
     locked at 1.4.7 (absinthe_plug) 939b6b9e
  - absinthe_phoenix 1.4.4 (Hex package) (mix)
    locked at 1.4.4 (absinthe_phoenix) af3b7b44`
* Client Framework and version (Relay, Apollo, etc): ExUnit test framework

### Expected behavior
`Absinthe.Pipeline.run()` expected to validate provided executable GQL document and parameters against schema.

```elixir
  def validate_graphql_docs() do
    options = [operation_name: "SomeMutation", variables: %{"message" => "string message"}]
    pipeline =
      My.Api.Schema
      |> Absinthe.Pipeline.for_document(options)
      |> Absinthe.Pipeline.without(Absinthe.Phase.Subscription.SubscribeSelf)
      |> Absinthe.Pipeline.without(Absinthe.Phase.Document.Execution.Resolution)
    case Absinthe.Pipeline.run(@badMutation, pipeline) do
      {:ok, %{execution: %{validation_errors: []}}, _} -> {:ok, []}
      {:ok, %{execution: %{validation_errors: validation_errors}}, _} -> {:error, validation_errors}
      other -> {:error, other}
    end
  end
```

### Actual behavior
Does the right thing given invalid data/parameters, but barfs on well-formed documents thus:
```elixir
     The following arguments were given to Absinthe.Phase.Document.Result.data/2:
         # 1
         nil
         # 2
         []
     Attempted function clauses (showing 5 out of 5):
         defp data(%{errors: [_ | _] = field_errors}, errors)
         defp data(%{value: nil}, errors)
         defp data(%{value: value, emitter: emitter}, errors)
         defp data(%{fields: fields}, errors)
         defp data(%{values: values}, errors)
     code: { status, errors } = GraphqlOps.validate_graphql_docs()
     stacktrace:
       (absinthe) lib/absinthe/phase/document/result.ex:50: Absinthe.Phase.Document.Result.data/2
       (absinthe) lib/absinthe/phase/document/result.ex:19: Absinthe.Phase.Document.Result.process/1
       (absinthe) lib/absinthe/phase/document/result.ex:11: Absinthe.Phase.Document.Result.run/2
       (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
       (pserver) lib/api/graphql_ops.ex:125: Pserver.Api.GraphqlOps.validate_graphql_docs/0
       test/pserver_api_test.exs:11: (test)
```

**Comment by ekobi** [comment]
Reproducing recommended workaround for the record:
```elixir
The easiest work around is to just set a value manually, by introducing a custom phase:

    pipeline =
      My.Api.Schema
      |> Absinthe.Pipeline.for_document(options)
      |> Absinthe.Pipeline.without(Absinthe.Phase.Subscription.SubscribeSelf)
      |> Absinthe.Pipeline.without(Absinthe.Phase.Document.Execution.Resolution)
      |> Absinthe.Pipeline.insert_before(Absinthe.Phase.Document.Result, MyApp.AbsintheFakeResult)

defmodule MyApp.AbsintheFakeResult do
  def run(blueprint, _) do
    blueprint = put_in(blueprint.execution.result, %{value: nil})
    {:ok, blueprint}
  end
end
```

**Comment by benwilson512** [comment]
Right, I think fundamentally the Result phase should just be made to work properly on documents with no execution result, which I think would be pretty easy.
